Repository antvis/insight-component, pull requests merged in 2023-01, with the labels that each got.

#5 feat: 色带选择器 - ColorRangeSelector
  src/components/formily/ColorPicker/AntdColorPicker/index.less
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/ColorPaletteGroup/index.less
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/ColorPaletteGroup/index.tsx
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/PaletteConfig/index.less
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/PaletteConfig/index.tsx
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/constants/color-ranges.ts
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/constants/index.ts
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/index.less
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/index.tsx
  src/components/formily/ColorRangeSelector/demos/default.tsx
  src/components/formily/ColorRangeSelector/index.md
  src/components/formily/ColorRangeSelector/index.tsx
  src/components/formily/RibbonSelect/AntdRibbonSelect/constants/ribbon-list.ts
  src/components/formily/index.ts
Labels: feature

#6 chore: ColorRangeSelector 组件 ColorRange 类型导出
  src/components/formily/index.ts
Labels: feature

#8 chore: 优化色带选择器选中思路
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/index.tsx
Labels: ignore-for-release

#7 fix: 色带选择器支持显示色带中不存在颜色bug修复
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/index.tsx
Labels: bugfix

#9 feat: 色带选择器支持自定义色带
  package.json
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/ColorPaletteGroup/index.less
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/ColorPaletteGroup/index.tsx
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/CustomRange/DragList/index.less
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/CustomRange/DragList/index.tsx
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/CustomRange/RangeItem/index.less
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/CustomRange/RangeItem/index.tsx
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/CustomRange/index.less
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/CustomRange/index.tsx
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/DropDownContent.tsx
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/PaletteConfig/index.less
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/PaletteConfig/index.tsx
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/index.less
  src/components/formily/ColorRangeSelector/AntdColorRangeSelector/index.tsx
  src/components/formily/ColorRangeSelector/index.tsx
Labels: feature
